services:
  seedgen:
    image: mcr.microsoft.com/powershell
    container_name: seed-generator
    volumes:
      - ./docker/db/init:/seed
      - ./generate-data-seed.ps1:/generate-data-seed.ps1:ro
    entrypoint: ["pwsh", "/generate-data-seed.ps1"]

  db:
    image: postgres:16
    container_name: postgres-db
    depends_on:
      seedgen:
        condition: service_completed_successfully
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: GIAS_prototype
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d

    # Ensures seed file exists AND runs entrypoint as postgres user
    command: >
      bash -c "
      echo 'Waiting for seed file...';
      while [ ! -f /docker-entrypoint-initdb.d/002-seed.sql ]; do
        sleep 1;
      done;

      echo 'Seed file found. Starting Postgres...';

      exec su postgres -c '/usr/local/bin/docker-entrypoint.sh postgres'
      "

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  dfe.getinformationaboutschools.prototyping.api:
    build:
      context: .
      dockerfile: ./src/API/Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=GIAS_prototype;Username=postgres;Password=postgres"
    ports:
      - "8080:8080"

volumes:
  db_data:
