name: Build No Cache

on:
  workflow_dispatch:

  # schedule:
  #   - cron: '30 12 * * 0'
    # Will run once a week on Sunday afternoon

jobs:
  build-no-cache:
    env:
      DOCKER_REPOSITORY: ghcr.io/dfe-digital/get-information-about-schools-api-prototype
    outputs:
      docker-image-tag: ${{ steps.build-image.outputs.tag }}
    permissions:
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout

    # Set up Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Login to GHCR
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build without cache and push docker image
      id: build-image
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.workspace }}
        file: ${{ github.workspace }}/src/API/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        docker-repository: ${{ env.DOCKER_REPOSITORY }}
        max-cache: true
        reuse-cache: false
        snyk-token: ${{ secrets.SNYK_TOKEN }}
        build-args: |
          GITHUB_USERNAME=${{ github.actor }}
        secrets: |
          github_token=${{ secrets.GITHUB_TOKEN }}

    - name: Notify teams channel on job failure
      if: ${{ failure() }}
      uses: DFE-Digital/github-actions/send-to-teams-channel@master
      with:
        teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
        title: "Build failure"
        service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
        message: |
          "Rebuild docker cache failure"