name: Build and Deploy
concurrency: build_and_deploy_${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy environment"
        required: true
        type: choice
        default: development
        options:
        - development
      docker-image-tag:
        description: "Docker image tag to deploy (optional)"
        required: true
        type: string

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled]

env:
  TERRAFORM_BASE: terraform/application

jobs:
  build:
    name: Build
    if: ${{ github.event_name != 'workflow_dispatch' }}
    env:
      DOCKER_REPOSITORY: ghcr.io/dfe-digital/get-information-about-schools-api-prototype
    outputs:
      docker-image-tag: ${{ steps.build-image.outputs.tag }}
    permissions:
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Set up Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Login to GHCR
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push image (this replaces the broken DFE action)
    - name: Build and push docker image
      id: build-image
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.workspace }}
        file: ${{ github.workspace }}/src/API/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          GITHUB_USERNAME=${{ github.actor }}
        secrets: |
          github_token=${{ secrets.GITHUB_TOKEN }}

  test:
    name: Run tests
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest

     # This is a skeleton test job
     # It will need to be updated to set the environment and run required tests
     # The steps can be moved to a separate action if preferred

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

     # - name: Run tests
     #   shell: bash
     #   run: |
     #     run some tests

  deploy:
    name: Deploy environments
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    environment:
       name: ${{ matrix.environment }}
       url: ${{ steps.deploy_app.outputs.environment_url }}
    needs: [build, test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write
    strategy:
      max-parallel: 1
      matrix:
        environment: [development]

    steps:
     - name: Set environment variables
       run: |
         source global_config/${DEPLOY_ENV}.sh
         tf_vars_file=${TF_VARS_PATH}/${DEPLOY_ENV}.tfvars.json
         echo " HEALTHCHECK_CMD=$(jq -r '.cluster' ${tf_vars_file})" >> $GITHUB_ENV

     - name: Deploy app to ${{ matrix.environment }}
       id: deploy_app
       uses: DFE-Digital/github-actions/deploy-to-aks@master
       with:
         azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
         azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         environment: ${{ matrix.environment }}
         sha: ${{ github.sha }}
         terraform-base: ${{ env.TERRAFORM_BASE }}
         healthcheck: ${{ env.HEALTHCHECK_CMD }}
         teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
         service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
         smoke-test: true
#        gcp-wip: ${{ vars.GCP_WIP }}
#        gcp-project-id: ${{ vars.GCP_PROJECT_ID }}

#   manual_deploy:
#     name: Manual deploy
#     if: ${{ github.event_name == 'workflow_dispatch' }}
#     environment:
#       name: ${{ inputs.environment }}
#       url: ${{ steps.deploy_manual.outputs.environment_url }}
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       pull-requests: write

#     steps:
#     - name: Deploy app to ${{ inputs.environment }}
#       id: deploy_manual
#       uses: DFE-Digital/github-actions/deploy-to-aks@master
#       with:
#         azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
#         azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#         azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#         environment: ${{ inputs.environment }}
#         pr-number: ${{ inputs.pull-request-number }}
#         sha: ${{ inputs.docker-image-tag }}
#         terraform-base: ${{ env.TERRAFORM_BASE }}
#         healthcheck: ${{ env.HEALTHCHECK_CMD }}
#         teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
#         service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
#         smoke-test: true
#         db-seed: ${{ inputs.environment == 'review' && 'true' || 'false' }}
# #        gcp-wip: ${{ vars.GCP_WIP }}
# #        gcp-project-id: ${{ vars.GCP_PROJECT_ID }}

#   deploy_domains_infra:
#     name: Deploy Domains Infrastructure
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#     concurrency: deploy_domains_infra
#     needs: [deploy]
#     environment:
#       name: production
#     permissions:
#       id-token: write

#     steps:
#     - name: Deploy Domains Infrastructure
#       uses: DFE-Digital/github-actions/deploy-domains-infra@master
#       with:
#         azure-client-id:  ${{ secrets.AZURE_CLIENT_ID  }}
#         azure-tenant-id:  ${{ secrets.AZURE_TENANT_ID   }}
#         azure-subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID   }}
#         teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
#         service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}

#   deploy_domains_env:
#     name: Deploy Domains to ${{ matrix.domain_environment }} environment
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#     concurrency: deploy_domains_${{ matrix.domain_environment }}
#     needs: [deploy_domains_infra]
#     strategy:
#       max-parallel: 1
#       matrix:
#         domain_environment: [development, production]
#     environment:
#       name: production
#     permissions:
#       id-token: write

#     steps:
#     - name: Deploy Domains Environment
#       uses: DFE-Digital/github-actions/deploy-domains-env@master
#       with:
#         azure-client-id:  ${{ secrets.AZURE_CLIENT_ID  }}
#         azure-tenant-id:  ${{ secrets.AZURE_TENANT_ID   }}
#         azure-subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID   }}
#         environment: ${{ matrix.domain_environment }}
#         healthcheck: healthcheck
#         teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
#         service: ${{ vars.TEAMS_MSG_SERVICE_NAME }}
